ssh_user: root
ssh_user_home: /root
# RELEASE must be a tagged version or release branch to pull cephadm from, probably just use the latest release, not main!
RELEASE: tentacle
# CEPHADM_REPO is the branch to actually deploy
# It can be a dev branch, e.g. CEPHADM_REPO: --dev wip-batrick-testing-20230808.012511
CEPHADM_REPO: --release tentacle
# Container image to use for cephadm bootstrap (and other cephadm operations when needed)
#CEPH_IMAGE: "quay.io/ceph/ceph:v20.2.0"
CEPH_IMAGE: "quay.ceph.io/edrodrig/ceph-v20.2.0:latest"
